//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estacionamento.Apresentacao.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckOut", ReplyAction="http://tempuri.org/IService1/CheckOutResponse")]
        double CheckOut(string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckOut", ReplyAction="http://tempuri.org/IService1/CheckOutResponse")]
        System.Threading.Tasks.Task<double> CheckOutAsync(string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckIn", ReplyAction="http://tempuri.org/IService1/CheckInResponse")]
        void CheckIn(string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckIn", ReplyAction="http://tempuri.org/IService1/CheckInResponse")]
        System.Threading.Tasks.Task CheckInAsync(string placa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Estacionamento.Apresentacao.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Estacionamento.Apresentacao.ServiceReference1.IService1>, Estacionamento.Apresentacao.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CheckOut(string placa) {
            return base.Channel.CheckOut(placa);
        }
        
        public System.Threading.Tasks.Task<double> CheckOutAsync(string placa) {
            return base.Channel.CheckOutAsync(placa);
        }
        
        public void CheckIn(string placa) {
            base.Channel.CheckIn(placa);
        }
        
        public System.Threading.Tasks.Task CheckInAsync(string placa) {
            return base.Channel.CheckInAsync(placa);
        }
    }
}
